### ISSUE TITLE
CloudFront 502: The Lambda function returned invalid json: The json output is not parsable

### ISSUE THREAD

**Issue by ivanpetrushev** [serverless-nextjs/serverless-next.js#525]
**Describe the bug**
Hello, guys. 

The Default Lambda@Edge for the deployed distribution returns json that CloudFront does not understand.

**To Reproduce**
When I visit https://xxxxxx.cloudfront.net/page/home I get this output:

```
502 ERROR
The request could not be satisfied.
The Lambda function returned invalid json: The json output is not parsable. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
```

It is weird that CloudFront Monitoring for that Lambda reports 100% success rate.
If I go check the logs (in the edge region Lambda was executed for me), I can't see any errors. There is some output related to the page render process, and at the end I get the default:

2020-07-29T12:32:09.058+03:00 | END RequestId: xxxx-yyyy-zzzz
2020-07-29T12:32:09.058+03:00 | REPORT RequestId: xxxx-yyyy-zzzz	Duration: 7438.78 ms	Billed Duration: 7450 ms	Memory Size: 512 MB	Max Memory Used: 254 MB

**Additional context**
nextjs: 9.5.0 (also appears in 9.4.4)
serverless-component: 1.15.0-alpha.5 (also appears in 1.16.0-alpha.0)

serverless.yml:
```
prj:
  component: "@sls-next/serverless-component@1.15.0-alpha.5"
  inputs:
    bucketName: prj-xxx-dev
    bucketRegion: eu-central-1
    useServerlessTraceTarget: true
    build:
      env:
        NEXT_PUBLIC_PORTAL: prj-xxx
        NEXT_PUBLIC_HIDE_EXTRA_OUTPUT: true
        NEXT_PUBLIC_STORYBLOK_DEVMODE: false
```

**Comment by danielcondemarin** [comment]
@ivanpetrushev Can you provide a simple repro?

**Comment by ivanpetrushev** [comment]
@danielcondemarin no, sorry, it is pretty convoluted app. I investigated further and it seems if there is any error rendering React, it will result in this ugly 502 CloudFront lambda error.

By "any error" I mean for example if the website renders fine in local browser, but there are any errors in the browser console. If there is anything red - the deployment lambda will break. This includes the most frequent errors like "unique keys", "invalid prop" or just any console.error()...

**Comment by danielcondemarin** [comment]
Without more details, ideally a repro I'm afraid I can't help here.

**Comment by peniakoff** [comment]
I found this issue too. For some requests I'm getting only 502 from AWS Cloudfront regarding to unparsable JSON. I'm trying to verify it with additional debug in the API lambda, but it is not so easy. I'm sure that response from server, which I'm requesting via this Lambda@Edge looks properly, but... maybe it is too large? IMO the problem is somewhere during coding to base64 and it depends on the response (JSON) size.

**Comment by dexter31** [comment]
+1 On this issue. I have an image lambda that is used for image optimization. Although I wasnt able to get the error response, I was able to isolate the cause.

All raw images(mine are webp by default) below 1MB seems to have no issues parsing, while anything above 1 MB goves out an invalid response.

**Comment by kartikag01** [comment]
+1 
I found this issue too after updating from 1.17.0-alpha.12 to 1.18.0 because of (TypeError: s3_static_assets_1.default is not a function) https://github.com/serverless-nextjs/serverless-next.js/issues/765 
i am facing this issue on some pages, which returns somewhat big jsons from getInitialProps.

NextJs version - 10.0.3

**Comment by Dayger666** [comment]
+1 found this issue too 
'@sls-next/serverless-component@1.17.1-alpha.1'

**Comment by SebastianSchenk** [comment]
+1 having the same issue. Sometimes, when I shrink down the window the mobile images are able to load, but most of the time it doesn't work. I found [this article](https://www.codejam.info/2021/02/lambda-json-output-not-parsable.html#:~:text=The%20Lambda%20function%20returned%20invalid%20JSON%3A%20the%20JSON%20output%20is%20not%20parsable,-February%2026%2C%202021&text=There%20could%20be%20a%20number,returning%20a%20poorly%20encoded%20response.) about size limits of lambda edge functions.

However, the few times it worked the files transmitted where around 400kb so I'm not sure if this is really the issue here.

**Comment by patricktyndall** [comment]
So what is the solution here, if we don't have control over the source images?

Is it just me, or does this seem like a real hinderance to this component's usability? 1MB _is_ a large size for images on the web, but it would be nice to have the option to go larger (again, if I don't have control over the source).

Things that have come to mind:
- Use the `deviceSizes` next config to limit requests for large-width images (this is imperfect because small-sized images with enough detail can easily be >1mb)
- (untested) Add `onError` to each `<Image />` and implement logic to fall back to the original URL in the event of a cloudfront 502

As a potential fix for this component, would it be possible for the component to detect this (should be able to determine the size of the output from within the handler), and when it's >1MB then return a redirect, so that we don't have the 502's any more?

**Comment by coltenkrauter** [comment]
I am having this issue as well. When my React app attempts to load a large image, I get a 502. When using a mobile device, a smaller optimized version of the same image is able to load just fine.

Requesting a large image in Google Chriome.
URL: `https://my-app-url.com/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fmontana.dd08ffca.jpg&w=1920&q=100`

<img width="680" alt="Screen Shot 2022-03-14 at 4 11 45 PM" src="https://user-images.githubusercontent.com/18080897/158275631-c9df3c99-e55a-4f3d-ba9f-36dbb07ebbdd.png">

@danielcondemarin, now that there are some more comments, do you have more context to provide guidance on this issue? Any help would be appreciated.

**Comment by coltenkrauter** [comment]
Related [Stack Overflow](https://stackoverflow.com/questions/55064286/lambdaedge-gives-502-only-for-some-images)

**Comment by brauliolledo** [comment]
For anyone reading this, make sure that your handler is marked as async if you're using return instead of callback. All examples on Lambda@Edge use callback so it's easy to miss.
